### ISSUE TITLE
MailClient Connection refused: no further information: smtp.gmail.com/74.125.135.109:587

### ISSUE THREAD

**Issue by Spotback** [vert-x3/vertx-mail-client#100]
I have an email utility which is currently using vertx mail client 3.6.3.  I have tried to send an email from multiple gmail accounts and get this same issue.  This utility was working fine on march 24th 2019. I have emails i recieved using my utility, and my last commit to my project was march 6th for my email utility. So nothing in my code has changed. I noticed this issue last night march 27 2019. So i went to this github repo and tried to see if the example would work still the same issue.

<h3>Vertx mail client example (https://github.com/vert-x3/vertx-mail-client)</h3>

```
public MailClient createClient2(Vertx vertx) {
        MailConfig config = new MailConfig();
        config.setHostname("smtp.gmail.com");
        config.setPort(587);
        config.setStarttls(StartTLSOptions.REQUIRED);
        config.setUsername("someEmail@gmail.com");
        config.setPassword("xyz");
        MailClient mailClient = MailClient.createNonShared(vertx, config);
        return mailClient;
    }

public MailMessage mailMessage() {
        MailMessage message = new MailMessage();
        message.setFrom("someEmail@gmail.com  ");
        message.setTo("someEmail2@outlook.com");
        message.setText("this is the plain message text");
        message.setHtml("this is html text <a href=\"http://vertx.io\">vertx.io</a>");
        return message;
    }

public void sendMail(Vertx vertx, MailMessage message, MailClient mailClient) {
        mailClient.sendMail(message, result -> {
            if (result.succeeded()) {
                System.out.println(result.result());
            } else {
                result.cause().printStackTrace();
            }
        });
    }
```

<h2>Here is the stack trace</h2>

```
Mar 28, 2019 10:53:20 AM io.vertx.ext.mail.impl.SMTPConnection
SEVERE: exception on connect
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: smtp.gmail.com/74.125.135.109:587
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused: no further information
	... 11 more

io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: smtp.gmail.com/74.125.135.109:587
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused: no further information
	... 11 more
```
Java 8
Maven 3.5.4

Any help on this issue would be greatly appreciated.

**Comment by Spotback** [comment]
Ive also done this with port 465 with ssl and login required and authMethod set to PLAIN

**Comment by gaol** [comment]
@Spotback Can you try `4.0.0-milestone4` which introduce the #126. It will try to switch to another authenticate mechanism if current one failed.
