### ISSUE TITLE
"General SSLEngine problem" error after upgrading to 3.2.1

### ISSUE THREAD

**Issue by thokari** [vert-x3/vertx-mail-client#62]
Hi i just upgraded everything to 3.2.1, now I am getting this error when calling `sendMail`:
```
SEVERE: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:391)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1375)
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:529)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:807)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:775)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1138)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1028)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:968)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:360)
	... 11 more
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1708)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:303)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:295)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1471)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:936)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:876)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:873)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1313)
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1164)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1067)
	... 13 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:281)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1458)
	... 21 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 27 more
```
Are there maybe any new options I have to set?
You can see the code here: https://github.com/thokari/vertx-kickstart

**Comment by alexlehm** [comment]
What kind of certificate are you using for the test server?
Then only change that might affect ssl handling in mail is that the hostname is resolved to ip address before the connect call, but that should not affect certificate checking.
I will take a look at the issue

**Comment by alexlehm** [comment]
MailDev supports STARTTLS which means that mail-client will try that and fail since the certificate is a selfsigned cert.
You can fix that by either turning off STARTTLS or setting ssl to trust all certificates in dev.json
````
    "emailServer": {
        "hostname": "localhost",
        "port": 1025,
        "trustAll": true
    }
````
or
````
    "emailServer": {
        "hostname": "localhost",
        "port": 1025,
        "starttls": "disabled"
    }
````
I am not sure why this should have changed between 3.2.0 and 3.2.1.

**Comment by thokari** [comment]
Hi, thanks! I was also wondering how I should give the properties, in case I am using Groovy. Actually I think I even tried setting the startTLS option on a Java Properties object, because I was not clear how the property names/types would map. Is there some general hint in the documentation somewhere?
Anyways continue the awesome!
