### ISSUE TITLE
Thread has been blocked when SMTPConnection.writeLine, V3.3.3

### ISSUE THREAD

**Issue by DaC1989** [vert-x3/vertx-mail-client#84]
when my attachment'size is large, about 5M, 
the thread checker would warn:
Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 8610 ms, time limit is 2000
io.vertx.core.VertxException: Thread blocked
	at sun.nio.cs.UTF_8$Encoder.encodeBufferLoop(UTF_8.java:682)
	at sun.nio.cs.UTF_8$Encoder.encodeLoop(UTF_8.java:693)
	at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:579)
	at io.netty.buffer.ByteBufUtil.encodeString0(ByteBufUtil.java:577)
	at io.netty.buffer.Unpooled.copiedBuffer(Unpooled.java:678)
	at io.netty.buffer.Unpooled.copiedBuffer(Unpooled.java:612)
	at io.vertx.core.net.impl.NetSocketImpl.write(NetSocketImpl.java:115)
	at io.vertx.ext.mail.impl.SMTPConnection.writeLine(SMTPConnection.java:141)
	at io.vertx.ext.mail.impl.SMTPSendMail.sendLineByLine(SMTPSendMail.java:220)
	at io.vertx.ext.mail.impl.SMTPSendMail.sendMaildata(SMTPSendMail.java:194)
	at io.vertx.ext.mail.impl.SMTPSendMail.lambda$dataCmd$2(SMTPSendMail.java:181

can we write buffer in work thread? so the event loop would not be blocked.

**Comment by alexlehm** [comment]
the write operation should not block, it will write until the write queue is full and then wait for it to drain. so its probably a bug I will take a look.
The MailConfig is not changeable after the MailClient is created, if you change the config including the password, you have to create a new MailClient.

**Comment by alexlehm** [comment]
@DaC1989 it would make sense to remove the 2nd question and either talk about the in google group or create a second issue with a question tag

**Comment by DaC1989** [comment]
@alexlehm OK.
 I think I could close the MailClient if the password changed

**Comment by alexlehm** [comment]
@DaC1989 I think I know where the issue comes from, but I am having trouble reproducing it. What system do you use and what kind of mail server (either local or remote, if remote, is it a public service)?

**Comment by alexlehm** [comment]
@DaC1989 I have added some debug logging to the code to be able to check the issue further. Could you build this branch as local maven project and run your program with debug level logging enabled?
https://github.com/alexlehm/vertx-mail-client/tree/localbranch/thread-blocked-writeline

**Comment by DaC1989** [comment]
@alexlehm i use mac OS sierra 10.12.3, and my mail server is remote, but it is my private service,  gadaddy server.
i will build this branch and  run my program with debug level logging enabled

**Comment by DaC1989** [comment]
@alexlehm i built that branch and run my program, but i didn't reproducing it. i will read the source code
