### ISSUE TITLE
error on vertx sendMail, io.vertx.core.impl.ContextImpl - Unhandled exception java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by dhacker21** [vert-x3/vertx-mail-client#95]
hello i cannot catch null error on sending email
my code is like this :

```
fun sendMessage(data: JsonObject) : Observable<MailResult> {
         return observable<MailResult> {
            val message = MailMessage(data)
            mailClient.sendMail(message, it)
         }.doOnError {
             log.error("error on mailClient, move to resend"+it.message + " "+ it.getStackTraceAsString())
         }.onErrorReturn {
             null
         }.map {
             it
         }
    }
```
and try to use this, but still cannot catch the error on failed : 

```
mailClient.sendMail(message) {
             if (it.succeeded()) {} 
             else {
                  log.error("error on mailClient "+it.cause().printStackTrace())
             }
}
```
log error :

```
io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.NullPointerException: null
    at io.vertx.ext.mail.impl.SMTPConnection.handleError(SMTPConnection.java:171)
    at io.vertx.ext.mail.impl.SMTPConnection.handleError(SMTPConnection.java:167)
    at io.vertx.ext.mail.impl.SMTPConnection.lambda$null$2(SMTPConnection.java:203)
    at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)
```
please help

**Comment by vietj** [comment]
@alexlehm can you have a look ?

**Comment by dhacker21** [comment]
already check SMTPConnection.java:203 is handleError("connection has been closed by the server")
but the error i get is : 
io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.NullPointerException: null
    at io.vertx.ext.mail.impl.SMTPConnection.handleError(SMTPConnection.java:171)
    at io.vertx.ext.mail.impl.SMTPConnection.handleError(SMTPConnection.java:167)
    at io.vertx.ext.mail.impl.SMTPConnection.lambda$null$2(SMTPConnection.java:203)
    at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)

**Comment by dhacker21** [comment]
hi, I finally i can catch the error : 

```
null java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
java.util.HashMap$KeyIterator.next(HashMap.java:1461)
io.vertx.ext.mail.impl.SMTPConnectionPool.getConnection0(SMTPConnectionPool.java:133)
io.vertx.ext.mail.impl.SMTPConnectionPool.getConnection(SMTPConnectionPool.java:77)
io.vertx.ext.mail.impl.MailClientImpl.getConnection(MailClientImpl.java:101)
io.vertx.ext.mail.impl.MailClientImpl.sendMail(MailClientImpl.java:91)
```
what error is this?

**Comment by dhacker21** [comment]
still cannot provide a reproducer, because the error is random,
and still got this error : 
```
io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.NullPointerException: null
    at io.vertx.ext.mail.impl.SMTPConnection.handleError(SMTPConnection.java:171)
    at io.vertx.ext.mail.impl.SMTPConnection.handleError(SMTPConnection.java:167)
    at io.vertx.ext.mail.impl.SMTPConnection.lambda$null$2(SMTPConnection.java:203)
    at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)
```
please help, i cannot catch that error

**Comment by dhacker21** [comment]
please update this  : 

try{
      for (SMTPConnection conn : allConnections) {
        if (conn != null && !conn.isBroken() && conn.isIdle()) {
          idleConn = conn;
          break;
        }
      }
    } catch (Exception e) {
      log.warn("error get all connections "+e.getMessage());
    }

**Comment by tsegismont** [comment]
@dhacker21 would like to contribute the fix?

**Comment by alexlehm** [comment]
@dhacker21 could you try a patched version of the module? I think I know how this happens, but I don't know how to reproduce it
the SMTPConnection class has an error handler that is set to null when the connection is returned to the pool so that any exception that happens then is not passed to the previous handler. The code doesn't check if the handler is null, it just calls the handleError message (this is a bug, it probably never appeared until now), this gives the stack trace you see.

````
  private void handleError(Throwable throwable) {
    if (errorHandler != null) {
      errorHandler.handle(throwable);
    } else {
      log.warn("handleError when no errorHandler is set", throwable);
    }
  }
````

**Comment by dhacker21** [comment]
Hi I just update this, and it fixed

`SMTPConnection idleConn = null;
    try {
      for (SMTPConnection conn : allConnections) {
        if (conn != null && !conn.isBroken() && conn.isIdle()) {
          idleConn = conn;
          break;
        }
      }
    } catch (Exception e) {
      log.warn("error get all connections "+e.getMessage());
    }`

**Comment by gaol** [comment]
I propose to close this issue as I cannot see NPE during long time(several hours) tests running in my local env on master branch.

**Comment by gaol** [comment]
Close it, if anyone does not agree, please feel free to reopen it. :)
